//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MusicCollection.Models
{
    public partial class Album
    {
        public long AlbumID { get; set; }
        public string Name { get; set; }
        public string Artist { get; set; }
        public string AlbumArtist { get; set; }
        public string Genre { get; set; }
        public Nullable<int> Year { get; set; }
        public int PlayCount { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<System.DateTime> LastPlayed { get; set; }
        public string ArtworkLocation { get; set; }
    }
    
}
